[buildPlans.JimmyCoffee]
family = "JimmyCoffee"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.JimmyCoffee.variants]
inherits = "ss14"

[buildPlans.JimmyCoffee.variants.design]
one = "base"
seven = "straight-serifless"
zero = "long-dotted"
capital-a = "straight-serifless"
capital-d = "standard-serifless"
capital-g = "toothed-serifless-hooked"
capital-j = "flat-hook-serifed"
capital-k = "straight-serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "standard-serifless"
capital-q = "crossing-curly-tailed"
capital-r = "straight-serifless"
capital-u = "toothed-serifless"
capital-w = "straight-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
d = "toothed-serifless"
f = "flat-hook-tailed"
g = "single-storey-flat-hook-serifless"
i = "serifed-semi-tailed"
j = "flat-hook-serifed"
k = "straight-serifless"
l = "serifed-semi-tailed"
m = "serifless"
n = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook-short-neck"
u = "toothed-serifless"
w = "straight-serifless"
y = "straight-turn-serifless"
punctuation-dot = "round"
underscore = "above-baseline"
caret = "low"
ascii-grave = "straight"
brace = "curly-flat-boundary"
ampersand = "closed"
at = "fourfold-solid-inner"
percent = "rings-continuous-slash"
lig-ltgteq = "flat"
lig-neq = "vertical"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"

[buildPlans.JimmyCoffee.ligations]
inherits = "dlig"

[buildPlans.JimmyCoffee.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.JimmyCoffee.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.JimmyCoffee.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
