include tokyonight/tokyo-night-kitty.conf

font_family Input Mono

font_features FiraCodeNF-Reg +cv02 +cv31 +ss01
font_features FiraCodeNF-Bold +cv02 +cv31 +ss01

font_features JetBrainsMonoNF-Regular +cv07 +cv12
font_features JetBrainsMonoNF-Bold +cv07 +cv12
font_features JetBrainsMonoNF-Italic +cv07 +cv12

font_features IntoneMonoNFM +ss01 +ss02 +ss03
font_features IntoneMonoNFM-Medium +ss01 +ss02 +ss03
font_features IntoneMonoNFM-Italic +ss01 +ss02 +ss03
font_features IntoneMonoNFM-MediumItalic +ss01 +ss02 +ss03

font_size 18
modify_font cell_height 110%

disable_ligatures never

confirm_os_window_close 0

background_opacity 0.92

map ctrl+q quit
